steps:
  # 1. Docker Build (BuildKit 활성화)
  - name: 'gcr.io/cloud-builders/docker'
    env: ['DOCKER_BUILDKIT=1']
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/app:latest',
      '-f', 'Dockerfile.prod',
      '.'
    ]

  # 2. Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/app:latest'
    id: Push

  # 3. Deploy to Cloud Run (업데이트)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - 'app'
      - '--platform=managed'
      - '--image=gcr.io/$PROJECT_ID/app:latest'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy

images:
  - 'gcr.io/$PROJECT_ID/app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
