steps:
  - name: 'gcr.io/cloud-builders/docker'
    env: ['DOCKER_BUILDKIT=1']
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/app:latest',
      '-f', 'Dockerfile.prod',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/app:latest'
options:
  logging: CLOUD_LOGGING_ONLY
